drop table if exists posts CASCADE;
create table posts
(
    id bigint generated by default as identity,
    title varchar(255),
    content varchar(255),
    writer varchar(255),
    primary key (id)
);